---
title: "Problem 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r engine = "bash"}
pwd
wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/proteomes/9606.tsv.gz
gunzip 9606.tsv.gz
```
```{r} 
#checking where I'm at
getwd()
list.files(getwd())
```


```{r}
#read the tsv file with colnames added manually, convert to aggregate list
pfam.table <- read.table("9606.tsv", sep = "\t", col.names = (c("seq id", "alignment start", 'alignment end', 'envelope start', "envelope end", "hmm acc", 'hmm name', 'type', 'hmm start', 'hmm end', 'hmm length', 'bit score', 'E-value', 'clan')))
head(pfam.table)
pfam.list<- as.list(pfam.table)
```
```{r}

#verifying that this function will give output if the given y is between to locations of envelope start and end
practice.function <- function(x, y) {
  if ((pfam.list$envelope.end[pfam.list$seq.id==x] >=y) & (pfam.list$envelope.start[pfam.list$seq.id==x] <=y)) 
    print("Okay")
}


#generates a dataframe of only positions with sequence id of interest

positions <- which(pfam.table$seq.id=="P17040")
#view the new dataframe
pfam.table[positions, ]

positions
#Loop through the new dataframe for the domains where the condition (comparing envelope start point/end point to our position/locus of interest (y) here) is true

for (row in 1:nrow(pfam.table[positions, ])){
    y <- 53
    if(as.integer(pfam.table[positions, ]$envelope.start[row]) <= y && as.integer(pfam.table[positions, ]$envelope.end[row]) >= y) {
      print(pfam.table[positions, ]$hmm.name[row])
    }
}

#repeat just to make sure it works with different seqid and position
positions2 <- which (pfam.table$seq.id=="F5H6A5")
#verify domains at sites of pfam.table[positions2, ]
pfam.table[positions2, ]


for (row in 1:nrow(pfam.table[positions2, ])){
    f <- 365
    if(as.integer(pfam.table[positions2, ]$envelope.start[row]) <= f && as.integer(pfam.table[positions2, ]$envelope.end[row]) >= f) {
      print(pfam.table[positions2, ]$hmm.name[row])
    }
}

#Not the prettiest but it gets the job done        

```

